### ISSUE TITLE
Delete local database?

### ISSUE THREAD

**Issue by Gambley1** [journeyapps/powersync.dart#15]
I have accidentally broken the local database when was playing around with Supabase and PowerSync. I have some data that has been de-syncronised with Supabase database and persist everytime I login into account. That means, when I am trying to delete these data locally, even though visually the data disappeared, data is not stored in Supabase database and after complete app restart it don't appear again, but when I log out from account and log in back the broken data appears again and I have no idea how to delete it or wipe.

First thing that came to my mind was to delete database and like re-fresh it and setup from scratch again, so everything broken will be deleted. However, I have no idea how to delete database using powersync sdk.

Maybe there are some others options to solve my problem, but I can not find them.

P.s. If you need to know what actually I have done that my data is broken, make sure to ask me.

**Comment by rkistner** [comment]
There is a known issue that when dropping a table, the data is not removed from PowerSync. We're working on a fix for this - should be out in the next week or so.

One notable cause is running [supabase db reset](https://supabase.com/docs/reference/cli/supabase-db-reset). This drops all tables and re-creates them using migrations, which causes this issue in PowerSync. Could this be what happened in your case?

As a workaround to recover from the issue, make a change to sync rules (e.g. add a comment) and deploy. This re-replicates all data from scratch, which should resolve the issue.

In production environments, make sure to always TRUNCATE a table before dropping.

**Comment by Gambley1** [comment]
Supabase db reset was not an actual issue that cased the problem with some data, however it is close to that. Instead, I manually dropped the table that was working with, without truncating (as you mentioned now), so that actually was the root of the problem.

I have tried to actually reset Supabase db and completely recreate the PowerSync project with the same sync rules. As a result, eventually,  it helped. The data now is correctly working and "ghost" data don't appear again and again. Newly create data works as expected. No sync rules errors are shown and generally everything seems to be working fine again.

Thanks so much for your quick response, it was actually helpful. Next time I will definitely take in mind to truncate a table before dropping.

**Comment by rkistner** [comment]
We've recently deployed some improvements related to how PowerSync handles schema changes, which should help with this. Specifically, dropping and re-creating a table should now be handled correctly as soon as you insert new data, where previously the old data (before dropping) would have remained indefinitely.

The new behavior is documented here:
https://docs.powersync.co/usage/lifecycle-maintenance/implementing-schema-changes#schema-changes-affecting-sync-rules
